field.formatter.settings.background_image_tools_media:
  type: mapping
  label: Background Media formatter settings.
  mapping:
    selector:
      type: string
      label: CSS Selector
    image_style:
      type: string
      label: Image Style
